modLoader = "javafml"
loaderVersion = "[41,)"
license = "MIT"
issueTrackerURL="https://github.com/TreyRuffy/BetterF3/issues/"

[[mods]]
modId = "betterf3"
version = "${version}"
displayName = "BetterF3"
updateJSONURL="https://api.modrinth.com/updates/betterf3/forge_updates.json"
displayURL="https://modrinth.com/mod/betterf3"
logoFile="icon.png"
authors = "TreyRuffy and cominixo"
description = '''
Better F3 for Minecraft Forge
Replaces Minecraft's original debug HUD with a highly customizable, more human-readable HUD.

The creator would like to thank:
- cominixo for creating the Fabric version of the mod
- Nirewen for creating the icon
'''

[[dependencies.betterf3]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.betterf3]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.betterf3]]
modId = "cloth_config"
versionRange = "[7.0.65,)"
mandatory = true
